---
- name: update all servers
  hosts: all
  become: yes
  tasks:
   - name: create info.txt with content on all servers
     copy:
       dest: /home/ec2-user/opt/devops/info.txt
       content: "hello from ansible!"
...  
